### Health Check
GET http://localhost:8000/hello

### Create knowledge item
POST http://localhost:8000/knowledge-items
Content-Type: application/json

{
  "title": "Project Management Best Practices",
  "content": "This document outlines the best practices for project management...",
  "itemType": "bestPractice",
  "metadata": {
    "author": "Jane Doe",
    "tags": ["project management", "best practices"],
    "department": "PMO",
    "projectContext": "enterprise"
  }
}

### Vector Search (metadata)
GET http://localhost:8000/knowledge-items/vector-search-metadata
    ?searchText=enterprise project management
    &top=10
    &department=PMO
    &projectContext=enterprise

### Vector Search (Content)
GET http://localhost:8000/knowledge-items/vector-search-content
    ?searchText=project management methodology
    &top=10
    &department=PMO

### Full Text Search(Title)
GET http://localhost:8000/knowledge-items/text-search-title
    ?searchText= project
    &top=10

### Full Text Search(Content)
GET http://localhost:8000/knowledge-items/text-search-content
    ?searchText=project management
    &top=10

### Hybrid Search-content (vector + full-text)
GET http://localhost:8000/knowledge-items/hybrid-search-content
    ?searchText=project management
    &top=10
    &department=PMO

### Hybrid Search-metadata (vector + full-text)
GET http://localhost:8000/knowledge-items/hybrid-search-metadata
    ?searchText=project management
    &top=10
    &department=PMO
### generate fake data
GET http://localhost:8000/generate-fake-knowledgeItems